/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CametRouteImport } from './routes/camet'
import { Route as ApplicationReceivedRouteImport } from './routes/application-received'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as GalleryWorkshopRouteImport } from './routes/gallery.workshop'
import { Route as GalleryTrainingRouteImport } from './routes/gallery.training'
import { Route as GalleryEquipmentRouteImport } from './routes/gallery.equipment'
import { Route as AboutInstructorsRouteImport } from './routes/about.instructors'
import { Route as AboutFounderRouteImport } from './routes/about.founder'
import { Route as AboutDirectorSvesRouteImport } from './routes/about.director-sves'
import { Route as AboutDirectorSsesRouteImport } from './routes/about.director-sses'
import { Route as AboutDirectorSaasRouteImport } from './routes/about.director-saas'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CametRoute = CametRouteImport.update({
  id: '/camet',
  path: '/camet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationReceivedRoute = ApplicationReceivedRouteImport.update({
  id: '/application-received',
  path: '/application-received',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const GalleryWorkshopRoute = GalleryWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryTrainingRoute = GalleryTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryEquipmentRoute = GalleryEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => GalleryRoute,
} as any)
const AboutInstructorsRoute = AboutInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AboutRoute,
} as any)
const AboutFounderRoute = AboutFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => AboutRoute,
} as any)
const AboutDirectorSvesRoute = AboutDirectorSvesRouteImport.update({
  id: '/director-sves',
  path: '/director-sves',
  getParentRoute: () => AboutRoute,
} as any)
const AboutDirectorSsesRoute = AboutDirectorSsesRouteImport.update({
  id: '/director-sses',
  path: '/director-sses',
  getParentRoute: () => AboutRoute,
} as any)
const AboutDirectorSaasRoute = AboutDirectorSaasRouteImport.update({
  id: '/director-saas',
  path: '/director-saas',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/application-received': typeof ApplicationReceivedRoute
  '/camet': typeof CametRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about/director-saas': typeof AboutDirectorSaasRoute
  '/about/director-sses': typeof AboutDirectorSsesRoute
  '/about/director-sves': typeof AboutDirectorSvesRoute
  '/about/founder': typeof AboutFounderRoute
  '/about/instructors': typeof AboutInstructorsRoute
  '/gallery/equipment': typeof GalleryEquipmentRoute
  '/gallery/training': typeof GalleryTrainingRoute
  '/gallery/workshop': typeof GalleryWorkshopRoute
  '/about/': typeof AboutIndexRoute
  '/gallery/': typeof GalleryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application-received': typeof ApplicationReceivedRoute
  '/camet': typeof CametRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about/director-saas': typeof AboutDirectorSaasRoute
  '/about/director-sses': typeof AboutDirectorSsesRoute
  '/about/director-sves': typeof AboutDirectorSvesRoute
  '/about/founder': typeof AboutFounderRoute
  '/about/instructors': typeof AboutInstructorsRoute
  '/gallery/equipment': typeof GalleryEquipmentRoute
  '/gallery/training': typeof GalleryTrainingRoute
  '/gallery/workshop': typeof GalleryWorkshopRoute
  '/about': typeof AboutIndexRoute
  '/gallery': typeof GalleryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/application-received': typeof ApplicationReceivedRoute
  '/camet': typeof CametRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about/director-saas': typeof AboutDirectorSaasRoute
  '/about/director-sses': typeof AboutDirectorSsesRoute
  '/about/director-sves': typeof AboutDirectorSvesRoute
  '/about/founder': typeof AboutFounderRoute
  '/about/instructors': typeof AboutInstructorsRoute
  '/gallery/equipment': typeof GalleryEquipmentRoute
  '/gallery/training': typeof GalleryTrainingRoute
  '/gallery/workshop': typeof GalleryWorkshopRoute
  '/about/': typeof AboutIndexRoute
  '/gallery/': typeof GalleryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/application-received'
    | '/camet'
    | '/contact'
    | '/gallery'
    | '/privacy'
    | '/programs'
    | '/sitemap.xml'
    | '/terms'
    | '/about/director-saas'
    | '/about/director-sses'
    | '/about/director-sves'
    | '/about/founder'
    | '/about/instructors'
    | '/gallery/equipment'
    | '/gallery/training'
    | '/gallery/workshop'
    | '/about/'
    | '/gallery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application-received'
    | '/camet'
    | '/contact'
    | '/privacy'
    | '/programs'
    | '/sitemap.xml'
    | '/terms'
    | '/about/director-saas'
    | '/about/director-sses'
    | '/about/director-sves'
    | '/about/founder'
    | '/about/instructors'
    | '/gallery/equipment'
    | '/gallery/training'
    | '/gallery/workshop'
    | '/about'
    | '/gallery'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/application-received'
    | '/camet'
    | '/contact'
    | '/gallery'
    | '/privacy'
    | '/programs'
    | '/sitemap.xml'
    | '/terms'
    | '/about/director-saas'
    | '/about/director-sses'
    | '/about/director-sves'
    | '/about/founder'
    | '/about/instructors'
    | '/gallery/equipment'
    | '/gallery/training'
    | '/gallery/workshop'
    | '/about/'
    | '/gallery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ApplicationReceivedRoute: typeof ApplicationReceivedRoute
  CametRoute: typeof CametRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camet': {
      id: '/camet'
      path: '/camet'
      fullPath: '/camet'
      preLoaderRoute: typeof CametRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-received': {
      id: '/application-received'
      path: '/application-received'
      fullPath: '/application-received'
      preLoaderRoute: typeof ApplicationReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/gallery/workshop': {
      id: '/gallery/workshop'
      path: '/workshop'
      fullPath: '/gallery/workshop'
      preLoaderRoute: typeof GalleryWorkshopRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/gallery/training': {
      id: '/gallery/training'
      path: '/training'
      fullPath: '/gallery/training'
      preLoaderRoute: typeof GalleryTrainingRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/gallery/equipment': {
      id: '/gallery/equipment'
      path: '/equipment'
      fullPath: '/gallery/equipment'
      preLoaderRoute: typeof GalleryEquipmentRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/about/instructors': {
      id: '/about/instructors'
      path: '/instructors'
      fullPath: '/about/instructors'
      preLoaderRoute: typeof AboutInstructorsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/founder': {
      id: '/about/founder'
      path: '/founder'
      fullPath: '/about/founder'
      preLoaderRoute: typeof AboutFounderRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/director-sves': {
      id: '/about/director-sves'
      path: '/director-sves'
      fullPath: '/about/director-sves'
      preLoaderRoute: typeof AboutDirectorSvesRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/director-sses': {
      id: '/about/director-sses'
      path: '/director-sses'
      fullPath: '/about/director-sses'
      preLoaderRoute: typeof AboutDirectorSsesRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/director-saas': {
      id: '/about/director-saas'
      path: '/director-saas'
      fullPath: '/about/director-saas'
      preLoaderRoute: typeof AboutDirectorSaasRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutDirectorSaasRoute: typeof AboutDirectorSaasRoute
  AboutDirectorSsesRoute: typeof AboutDirectorSsesRoute
  AboutDirectorSvesRoute: typeof AboutDirectorSvesRoute
  AboutFounderRoute: typeof AboutFounderRoute
  AboutInstructorsRoute: typeof AboutInstructorsRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutDirectorSaasRoute: AboutDirectorSaasRoute,
  AboutDirectorSsesRoute: AboutDirectorSsesRoute,
  AboutDirectorSvesRoute: AboutDirectorSvesRoute,
  AboutFounderRoute: AboutFounderRoute,
  AboutInstructorsRoute: AboutInstructorsRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface GalleryRouteChildren {
  GalleryEquipmentRoute: typeof GalleryEquipmentRoute
  GalleryTrainingRoute: typeof GalleryTrainingRoute
  GalleryWorkshopRoute: typeof GalleryWorkshopRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryEquipmentRoute: GalleryEquipmentRoute,
  GalleryTrainingRoute: GalleryTrainingRoute,
  GalleryWorkshopRoute: GalleryWorkshopRoute,
  GalleryIndexRoute: GalleryIndexRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ApplicationReceivedRoute: ApplicationReceivedRoute,
  CametRoute: CametRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
